package com.learn.entity;

public class TClassGroupCourseKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_class_group_course.f_class_group_id
     *
     * @mbg.generated
     */
    private Integer fClassGroupId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_class_group_course.f_course_id
     *
     * @mbg.generated
     */
    private Integer fCourseId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_class_group_course.f_class_group_id
     *
     * @return the value of t_class_group_course.f_class_group_id
     *
     * @mbg.generated
     */
    public Integer getfClassGroupId() {
        return fClassGroupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_class_group_course.f_class_group_id
     *
     * @param fClassGroupId the value for t_class_group_course.f_class_group_id
     *
     * @mbg.generated
     */
    public void setfClassGroupId(Integer fClassGroupId) {
        this.fClassGroupId = fClassGroupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_class_group_course.f_course_id
     *
     * @return the value of t_class_group_course.f_course_id
     *
     * @mbg.generated
     */
    public Integer getfCourseId() {
        return fCourseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_class_group_course.f_course_id
     *
     * @param fCourseId the value for t_class_group_course.f_course_id
     *
     * @mbg.generated
     */
    public void setfCourseId(Integer fCourseId) {
        this.fCourseId = fCourseId;
    }
}