package com.learn.entity;

public class TClassGroup {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_class_group.f_class_goup_id
     *
     * @mbg.generated
     */
    private Integer fClassGoupId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_class_group.f_class_goup_name
     *
     * @mbg.generated
     */
    private String fClassGoupName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_class_group.f_class_goup_id
     *
     * @return the value of t_class_group.f_class_goup_id
     *
     * @mbg.generated
     */
    public Integer getfClassGoupId() {
        return fClassGoupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_class_group.f_class_goup_id
     *
     * @param fClassGoupId the value for t_class_group.f_class_goup_id
     *
     * @mbg.generated
     */
    public void setfClassGoupId(Integer fClassGoupId) {
        this.fClassGoupId = fClassGoupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_class_group.f_class_goup_name
     *
     * @return the value of t_class_group.f_class_goup_name
     *
     * @mbg.generated
     */
    public String getfClassGoupName() {
        return fClassGoupName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_class_group.f_class_goup_name
     *
     * @param fClassGoupName the value for t_class_group.f_class_goup_name
     *
     * @mbg.generated
     */
    public void setfClassGoupName(String fClassGoupName) {
        this.fClassGoupName = fClassGoupName == null ? null : fClassGoupName.trim();
    }
}