package com.learn.entity;

public class TClassCourseNum extends TClassCourseNumKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_class_course_num.f_course_num
     *
     * @mbg.generated
     */
    private Integer fCourseNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_class_course_num.f_constrain
     *
     * @mbg.generated
     */
    private Integer fConstrain;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_class_course_num.f_course_num
     *
     * @return the value of t_class_course_num.f_course_num
     *
     * @mbg.generated
     */
    public Integer getfCourseNum() {
        return fCourseNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_class_course_num.f_course_num
     *
     * @param fCourseNum the value for t_class_course_num.f_course_num
     *
     * @mbg.generated
     */
    public void setfCourseNum(Integer fCourseNum) {
        this.fCourseNum = fCourseNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_class_course_num.f_constrain
     *
     * @return the value of t_class_course_num.f_constrain
     *
     * @mbg.generated
     */
    public Integer getfConstrain() {
        return fConstrain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_class_course_num.f_constrain
     *
     * @param fConstrain the value for t_class_course_num.f_constrain
     *
     * @mbg.generated
     */
    public void setfConstrain(Integer fConstrain) {
        this.fConstrain = fConstrain;
    }
}