package com.learn.entity;

public class TClassCourse extends TClassCourseKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_class_course.f_course_count
     *
     * @mbg.generated
     */
    private Integer fCourseCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_class_course.f_have_course_count
     *
     * @mbg.generated
     */
    private Integer fHaveCourseCount;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_class_course.f_course_count
     *
     * @return the value of t_class_course.f_course_count
     *
     * @mbg.generated
     */
    public Integer getfCourseCount() {
        return fCourseCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_class_course.f_course_count
     *
     * @param fCourseCount the value for t_class_course.f_course_count
     *
     * @mbg.generated
     */
    public void setfCourseCount(Integer fCourseCount) {
        this.fCourseCount = fCourseCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_class_course.f_have_course_count
     *
     * @return the value of t_class_course.f_have_course_count
     *
     * @mbg.generated
     */
    public Integer getfHaveCourseCount() {
        return fHaveCourseCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_class_course.f_have_course_count
     *
     * @param fHaveCourseCount the value for t_class_course.f_have_course_count
     *
     * @mbg.generated
     */
    public void setfHaveCourseCount(Integer fHaveCourseCount) {
        this.fHaveCourseCount = fHaveCourseCount;
    }
}