package com.learn.entity;

public class TClass {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_class.f_class_id
     *
     * @mbg.generated
     */
    private Integer fClassId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_class.f_class_name
     *
     * @mbg.generated
     */
    private String fClassName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_class.f_class_goup_id
     *
     * @mbg.generated
     */
    private Integer fClassGoupId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_class.f_class_id
     *
     * @return the value of t_class.f_class_id
     *
     * @mbg.generated
     */
    public Integer getfClassId() {
        return fClassId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_class.f_class_id
     *
     * @param fClassId the value for t_class.f_class_id
     *
     * @mbg.generated
     */
    public void setfClassId(Integer fClassId) {
        this.fClassId = fClassId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_class.f_class_name
     *
     * @return the value of t_class.f_class_name
     *
     * @mbg.generated
     */
    public String getfClassName() {
        return fClassName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_class.f_class_name
     *
     * @param fClassName the value for t_class.f_class_name
     *
     * @mbg.generated
     */
    public void setfClassName(String fClassName) {
        this.fClassName = fClassName == null ? null : fClassName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_class.f_class_goup_id
     *
     * @return the value of t_class.f_class_goup_id
     *
     * @mbg.generated
     */
    public Integer getfClassGoupId() {
        return fClassGoupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_class.f_class_goup_id
     *
     * @param fClassGoupId the value for t_class.f_class_goup_id
     *
     * @mbg.generated
     */
    public void setfClassGoupId(Integer fClassGoupId) {
        this.fClassGoupId = fClassGoupId;
    }
}