package com.learn.entity;

public class TContraintsColor {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_contraints_color.f_contraints_id
     *
     * @mbg.generated
     */
    private Integer fContraintsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_contraints_color.f_color
     *
     * @mbg.generated
     */
    private String fColor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_contraints_color.f_value
     *
     * @mbg.generated
     */
    private Integer fValue;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_contraints_color.f_contraints_id
     *
     * @return the value of t_contraints_color.f_contraints_id
     *
     * @mbg.generated
     */
    public Integer getfContraintsId() {
        return fContraintsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_contraints_color.f_contraints_id
     *
     * @param fContraintsId the value for t_contraints_color.f_contraints_id
     *
     * @mbg.generated
     */
    public void setfContraintsId(Integer fContraintsId) {
        this.fContraintsId = fContraintsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_contraints_color.f_color
     *
     * @return the value of t_contraints_color.f_color
     *
     * @mbg.generated
     */
    public String getfColor() {
        return fColor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_contraints_color.f_color
     *
     * @param fColor the value for t_contraints_color.f_color
     *
     * @mbg.generated
     */
    public void setfColor(String fColor) {
        this.fColor = fColor == null ? null : fColor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_contraints_color.f_value
     *
     * @return the value of t_contraints_color.f_value
     *
     * @mbg.generated
     */
    public Integer getfValue() {
        return fValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_contraints_color.f_value
     *
     * @param fValue the value for t_contraints_color.f_value
     *
     * @mbg.generated
     */
    public void setfValue(Integer fValue) {
        this.fValue = fValue;
    }
}