package com.learn.entity;

public class TCount {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_count.f_count_id
     *
     * @mbg.generated
     */
    private Integer fCountId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_count.f_count_name
     *
     * @mbg.generated
     */
    private String fCountName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_count.f_count_type
     *
     * @mbg.generated
     */
    private Integer fCountType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_count.f_count_id
     *
     * @return the value of t_count.f_count_id
     *
     * @mbg.generated
     */
    public Integer getfCountId() {
        return fCountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_count.f_count_id
     *
     * @param fCountId the value for t_count.f_count_id
     *
     * @mbg.generated
     */
    public void setfCountId(Integer fCountId) {
        this.fCountId = fCountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_count.f_count_name
     *
     * @return the value of t_count.f_count_name
     *
     * @mbg.generated
     */
    public String getfCountName() {
        return fCountName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_count.f_count_name
     *
     * @param fCountName the value for t_count.f_count_name
     *
     * @mbg.generated
     */
    public void setfCountName(String fCountName) {
        this.fCountName = fCountName == null ? null : fCountName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_count.f_count_type
     *
     * @return the value of t_count.f_count_type
     *
     * @mbg.generated
     */
    public Integer getfCountType() {
        return fCountType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_count.f_count_type
     *
     * @param fCountType the value for t_count.f_count_type
     *
     * @mbg.generated
     */
    public void setfCountType(Integer fCountType) {
        this.fCountType = fCountType;
    }
}