package com.learn.entity;

public class TCourseWhere extends TCourseWhereKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_course_where.f_course_type
     *
     * @mbg.generated
     */
    private Integer fCourseType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_course_where.f_course_type
     *
     * @return the value of t_course_where.f_course_type
     *
     * @mbg.generated
     */
    public Integer getfCourseType() {
        return fCourseType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_course_where.f_course_type
     *
     * @param fCourseType the value for t_course_where.f_course_type
     *
     * @mbg.generated
     */
    public void setfCourseType(Integer fCourseType) {
        this.fCourseType = fCourseType;
    }
}