package com.learn.entity;

public class TCourseWhereKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_course_where.f_course_id
     *
     * @mbg.generated
     */
    private Integer fCourseId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_course_where.f_week_id
     *
     * @mbg.generated
     */
    private Integer fWeekId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_course_where.f_count_id
     *
     * @mbg.generated
     */
    private Integer fCountId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_course_where.f_course_id
     *
     * @return the value of t_course_where.f_course_id
     *
     * @mbg.generated
     */
    public Integer getfCourseId() {
        return fCourseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_course_where.f_course_id
     *
     * @param fCourseId the value for t_course_where.f_course_id
     *
     * @mbg.generated
     */
    public void setfCourseId(Integer fCourseId) {
        this.fCourseId = fCourseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_course_where.f_week_id
     *
     * @return the value of t_course_where.f_week_id
     *
     * @mbg.generated
     */
    public Integer getfWeekId() {
        return fWeekId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_course_where.f_week_id
     *
     * @param fWeekId the value for t_course_where.f_week_id
     *
     * @mbg.generated
     */
    public void setfWeekId(Integer fWeekId) {
        this.fWeekId = fWeekId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_course_where.f_count_id
     *
     * @return the value of t_course_where.f_count_id
     *
     * @mbg.generated
     */
    public Integer getfCountId() {
        return fCountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_course_where.f_count_id
     *
     * @param fCountId the value for t_course_where.f_count_id
     *
     * @mbg.generated
     */
    public void setfCountId(Integer fCountId) {
        this.fCountId = fCountId;
    }
}