package com.learn.entity;

public class TCourse {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_course.f_course_id
     *
     * @mbg.generated
     */
    private Integer fCourseId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_course.f_course_name
     *
     * @mbg.generated
     */
    private String fCourseName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_course.f_course_flag_id
     *
     * @mbg.generated
     */
    private Integer fCourseFlagId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_course.f_course_id
     *
     * @return the value of t_course.f_course_id
     *
     * @mbg.generated
     */
    public Integer getfCourseId() {
        return fCourseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_course.f_course_id
     *
     * @param fCourseId the value for t_course.f_course_id
     *
     * @mbg.generated
     */
    public void setfCourseId(Integer fCourseId) {
        this.fCourseId = fCourseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_course.f_course_name
     *
     * @return the value of t_course.f_course_name
     *
     * @mbg.generated
     */
    public String getfCourseName() {
        return fCourseName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_course.f_course_name
     *
     * @param fCourseName the value for t_course.f_course_name
     *
     * @mbg.generated
     */
    public void setfCourseName(String fCourseName) {
        this.fCourseName = fCourseName == null ? null : fCourseName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_course.f_course_flag_id
     *
     * @return the value of t_course.f_course_flag_id
     *
     * @mbg.generated
     */
    public Integer getfCourseFlagId() {
        return fCourseFlagId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_course.f_course_flag_id
     *
     * @param fCourseFlagId the value for t_course.f_course_flag_id
     *
     * @mbg.generated
     */
    public void setfCourseFlagId(Integer fCourseFlagId) {
        this.fCourseFlagId = fCourseFlagId;
    }
}