package com.learn.entity;

public class TempSchoolTimeTable extends TempSchoolTimeTableKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column temp_school_time_table.f_course_num
     *
     * @mbg.generated
     */
    private Integer fCourseNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column temp_school_time_table.f_conefict_flag
     *
     * @mbg.generated
     */
    private Integer fConefictFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column temp_school_time_table.f_type_conefict_id
     *
     * @mbg.generated
     */
    private Integer fTypeConefictId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column temp_school_time_table.f_class_conefict_id
     *
     * @mbg.generated
     */
    private Integer fClassConefictId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column temp_school_time_table.f_course_type
     *
     * @mbg.generated
     */
    private Integer fCourseType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column temp_school_time_table.f_course_num
     *
     * @return the value of temp_school_time_table.f_course_num
     *
     * @mbg.generated
     */
    public Integer getfCourseNum() {
        return fCourseNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column temp_school_time_table.f_course_num
     *
     * @param fCourseNum the value for temp_school_time_table.f_course_num
     *
     * @mbg.generated
     */
    public void setfCourseNum(Integer fCourseNum) {
        this.fCourseNum = fCourseNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column temp_school_time_table.f_conefict_flag
     *
     * @return the value of temp_school_time_table.f_conefict_flag
     *
     * @mbg.generated
     */
    public Integer getfConefictFlag() {
        return fConefictFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column temp_school_time_table.f_conefict_flag
     *
     * @param fConefictFlag the value for temp_school_time_table.f_conefict_flag
     *
     * @mbg.generated
     */
    public void setfConefictFlag(Integer fConefictFlag) {
        this.fConefictFlag = fConefictFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column temp_school_time_table.f_type_conefict_id
     *
     * @return the value of temp_school_time_table.f_type_conefict_id
     *
     * @mbg.generated
     */
    public Integer getfTypeConefictId() {
        return fTypeConefictId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column temp_school_time_table.f_type_conefict_id
     *
     * @param fTypeConefictId the value for temp_school_time_table.f_type_conefict_id
     *
     * @mbg.generated
     */
    public void setfTypeConefictId(Integer fTypeConefictId) {
        this.fTypeConefictId = fTypeConefictId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column temp_school_time_table.f_class_conefict_id
     *
     * @return the value of temp_school_time_table.f_class_conefict_id
     *
     * @mbg.generated
     */
    public Integer getfClassConefictId() {
        return fClassConefictId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column temp_school_time_table.f_class_conefict_id
     *
     * @param fClassConefictId the value for temp_school_time_table.f_class_conefict_id
     *
     * @mbg.generated
     */
    public void setfClassConefictId(Integer fClassConefictId) {
        this.fClassConefictId = fClassConefictId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column temp_school_time_table.f_course_type
     *
     * @return the value of temp_school_time_table.f_course_type
     *
     * @mbg.generated
     */
    public Integer getfCourseType() {
        return fCourseType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column temp_school_time_table.f_course_type
     *
     * @param fCourseType the value for temp_school_time_table.f_course_type
     *
     * @mbg.generated
     */
    public void setfCourseType(Integer fCourseType) {
        this.fCourseType = fCourseType;
    }
}