package com.learn.entity;

public class TempSchoolTimeTableKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column temp_school_time_table.f_week_id
     *
     * @mbg.generated
     */
    private Integer fWeekId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column temp_school_time_table.f_count_id
     *
     * @mbg.generated
     */
    private Integer fCountId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column temp_school_time_table.f_teacher_id
     *
     * @mbg.generated
     */
    private Integer fTeacherId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column temp_school_time_table.f_class_id
     *
     * @mbg.generated
     */
    private Integer fClassId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column temp_school_time_table.f_course_id
     *
     * @mbg.generated
     */
    private Integer fCourseId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column temp_school_time_table.f_week_id
     *
     * @return the value of temp_school_time_table.f_week_id
     *
     * @mbg.generated
     */
    public Integer getfWeekId() {
        return fWeekId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column temp_school_time_table.f_week_id
     *
     * @param fWeekId the value for temp_school_time_table.f_week_id
     *
     * @mbg.generated
     */
    public void setfWeekId(Integer fWeekId) {
        this.fWeekId = fWeekId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column temp_school_time_table.f_count_id
     *
     * @return the value of temp_school_time_table.f_count_id
     *
     * @mbg.generated
     */
    public Integer getfCountId() {
        return fCountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column temp_school_time_table.f_count_id
     *
     * @param fCountId the value for temp_school_time_table.f_count_id
     *
     * @mbg.generated
     */
    public void setfCountId(Integer fCountId) {
        this.fCountId = fCountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column temp_school_time_table.f_teacher_id
     *
     * @return the value of temp_school_time_table.f_teacher_id
     *
     * @mbg.generated
     */
    public Integer getfTeacherId() {
        return fTeacherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column temp_school_time_table.f_teacher_id
     *
     * @param fTeacherId the value for temp_school_time_table.f_teacher_id
     *
     * @mbg.generated
     */
    public void setfTeacherId(Integer fTeacherId) {
        this.fTeacherId = fTeacherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column temp_school_time_table.f_class_id
     *
     * @return the value of temp_school_time_table.f_class_id
     *
     * @mbg.generated
     */
    public Integer getfClassId() {
        return fClassId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column temp_school_time_table.f_class_id
     *
     * @param fClassId the value for temp_school_time_table.f_class_id
     *
     * @mbg.generated
     */
    public void setfClassId(Integer fClassId) {
        this.fClassId = fClassId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column temp_school_time_table.f_course_id
     *
     * @return the value of temp_school_time_table.f_course_id
     *
     * @mbg.generated
     */
    public Integer getfCourseId() {
        return fCourseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column temp_school_time_table.f_course_id
     *
     * @param fCourseId the value for temp_school_time_table.f_course_id
     *
     * @mbg.generated
     */
    public void setfCourseId(Integer fCourseId) {
        this.fCourseId = fCourseId;
    }
}