package com.learn.entity;

public class TTempKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_temp.f_class_id
     *
     * @mbg.generated
     */
    private Integer fClassId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_temp.f_course_id
     *
     * @mbg.generated
     */
    private Integer fCourseId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_temp.f_teacher_id
     *
     * @mbg.generated
     */
    private Integer fTeacherId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_temp.f_class_id
     *
     * @return the value of t_temp.f_class_id
     *
     * @mbg.generated
     */
    public Integer getfClassId() {
        return fClassId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_temp.f_class_id
     *
     * @param fClassId the value for t_temp.f_class_id
     *
     * @mbg.generated
     */
    public void setfClassId(Integer fClassId) {
        this.fClassId = fClassId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_temp.f_course_id
     *
     * @return the value of t_temp.f_course_id
     *
     * @mbg.generated
     */
    public Integer getfCourseId() {
        return fCourseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_temp.f_course_id
     *
     * @param fCourseId the value for t_temp.f_course_id
     *
     * @mbg.generated
     */
    public void setfCourseId(Integer fCourseId) {
        this.fCourseId = fCourseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_temp.f_teacher_id
     *
     * @return the value of t_temp.f_teacher_id
     *
     * @mbg.generated
     */
    public Integer getfTeacherId() {
        return fTeacherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_temp.f_teacher_id
     *
     * @param fTeacherId the value for t_temp.f_teacher_id
     *
     * @mbg.generated
     */
    public void setfTeacherId(Integer fTeacherId) {
        this.fTeacherId = fTeacherId;
    }
}