package com.learn.entity;

public class TTemp extends TTempKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_temp.f_course_count
     *
     * @mbg.generated
     */
    private Integer fCourseCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_temp.f_undonetimes
     *
     * @mbg.generated
     */
    private Integer fUndonetimes;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_temp.f_turned
     *
     * @mbg.generated
     */
    private Integer fTurned;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_temp.f_course_count
     *
     * @return the value of t_temp.f_course_count
     *
     * @mbg.generated
     */
    public Integer getfCourseCount() {
        return fCourseCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_temp.f_course_count
     *
     * @param fCourseCount the value for t_temp.f_course_count
     *
     * @mbg.generated
     */
    public void setfCourseCount(Integer fCourseCount) {
        this.fCourseCount = fCourseCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_temp.f_undonetimes
     *
     * @return the value of t_temp.f_undonetimes
     *
     * @mbg.generated
     */
    public Integer getfUndonetimes() {
        return fUndonetimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_temp.f_undonetimes
     *
     * @param fUndonetimes the value for t_temp.f_undonetimes
     *
     * @mbg.generated
     */
    public void setfUndonetimes(Integer fUndonetimes) {
        this.fUndonetimes = fUndonetimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_temp.f_turned
     *
     * @return the value of t_temp.f_turned
     *
     * @mbg.generated
     */
    public Integer getfTurned() {
        return fTurned;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_temp.f_turned
     *
     * @param fTurned the value for t_temp.f_turned
     *
     * @mbg.generated
     */
    public void setfTurned(Integer fTurned) {
        this.fTurned = fTurned;
    }
}