package com.learn.entity;

public class TUser {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.f_user_id
     *
     * @mbg.generated
     */
    private Integer fUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.f_count_name
     *
     * @mbg.generated
     */
    private String fCountName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.f_count_pass
     *
     * @mbg.generated
     */
    private String fCountPass;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.f_count_title
     *
     * @mbg.generated
     */
    private String fCountTitle;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.f_user_id
     *
     * @return the value of t_user.f_user_id
     *
     * @mbg.generated
     */
    public Integer getfUserId() {
        return fUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.f_user_id
     *
     * @param fUserId the value for t_user.f_user_id
     *
     * @mbg.generated
     */
    public void setfUserId(Integer fUserId) {
        this.fUserId = fUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.f_count_name
     *
     * @return the value of t_user.f_count_name
     *
     * @mbg.generated
     */
    public String getfCountName() {
        return fCountName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.f_count_name
     *
     * @param fCountName the value for t_user.f_count_name
     *
     * @mbg.generated
     */
    public void setfCountName(String fCountName) {
        this.fCountName = fCountName == null ? null : fCountName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.f_count_pass
     *
     * @return the value of t_user.f_count_pass
     *
     * @mbg.generated
     */
    public String getfCountPass() {
        return fCountPass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.f_count_pass
     *
     * @param fCountPass the value for t_user.f_count_pass
     *
     * @mbg.generated
     */
    public void setfCountPass(String fCountPass) {
        this.fCountPass = fCountPass == null ? null : fCountPass.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.f_count_title
     *
     * @return the value of t_user.f_count_title
     *
     * @mbg.generated
     */
    public String getfCountTitle() {
        return fCountTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.f_count_title
     *
     * @param fCountTitle the value for t_user.f_count_title
     *
     * @mbg.generated
     */
    public void setfCountTitle(String fCountTitle) {
        this.fCountTitle = fCountTitle == null ? null : fCountTitle.trim();
    }
}