package com.learn.entity;

public class TWeek {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_week.f_week_id
     *
     * @mbg.generated
     */
    private Integer fWeekId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_week.f_week_name
     *
     * @mbg.generated
     */
    private String fWeekName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_week.f_week_flag
     *
     * @mbg.generated
     */
    private Integer fWeekFlag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_week.f_week_id
     *
     * @return the value of t_week.f_week_id
     *
     * @mbg.generated
     */
    public Integer getfWeekId() {
        return fWeekId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_week.f_week_id
     *
     * @param fWeekId the value for t_week.f_week_id
     *
     * @mbg.generated
     */
    public void setfWeekId(Integer fWeekId) {
        this.fWeekId = fWeekId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_week.f_week_name
     *
     * @return the value of t_week.f_week_name
     *
     * @mbg.generated
     */
    public String getfWeekName() {
        return fWeekName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_week.f_week_name
     *
     * @param fWeekName the value for t_week.f_week_name
     *
     * @mbg.generated
     */
    public void setfWeekName(String fWeekName) {
        this.fWeekName = fWeekName == null ? null : fWeekName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_week.f_week_flag
     *
     * @return the value of t_week.f_week_flag
     *
     * @mbg.generated
     */
    public Integer getfWeekFlag() {
        return fWeekFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_week.f_week_flag
     *
     * @param fWeekFlag the value for t_week.f_week_flag
     *
     * @mbg.generated
     */
    public void setfWeekFlag(Integer fWeekFlag) {
        this.fWeekFlag = fWeekFlag;
    }
}