package com.learn.paik.dao;

import com.learn.entity.TClassCourseNum;
import com.learn.entity.TClassCourseNumKey;

public interface TClassCourseNumMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_class_course_num
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(TClassCourseNumKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_class_course_num
     *
     * @mbg.generated
     */
    int insert(TClassCourseNum record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_class_course_num
     *
     * @mbg.generated
     */
    int insertSelective(TClassCourseNum record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_class_course_num
     *
     * @mbg.generated
     */
    TClassCourseNum selectByPrimaryKey(TClassCourseNumKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_class_course_num
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TClassCourseNum record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_class_course_num
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TClassCourseNum record);
}