package com.learn.paik.dao;

import com.learn.entity.TClassCourse;
import com.learn.entity.TClassCourseKey;

public interface TClassCourseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_class_course
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(TClassCourseKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_class_course
     *
     * @mbg.generated
     */
    int insert(TClassCourse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_class_course
     *
     * @mbg.generated
     */
    int insertSelective(TClassCourse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_class_course
     *
     * @mbg.generated
     */
    TClassCourse selectByPrimaryKey(TClassCourseKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_class_course
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TClassCourse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_class_course
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TClassCourse record);
}