package com.learn.paik.dao;

import com.learn.entity.TClass;

public interface TClassMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_class
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer fClassId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_class
     *
     * @mbg.generated
     */
    int insert(TClass record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_class
     *
     * @mbg.generated
     */
    int insertSelective(TClass record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_class
     *
     * @mbg.generated
     */
    TClass selectByPrimaryKey(Integer fClassId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_class
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TClass record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_class
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TClass record);
}