package com.learn.paik.dao;

import com.learn.entity.TContraintsColor;

public interface TContraintsColorMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_contraints_color
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer fContraintsId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_contraints_color
     *
     * @mbg.generated
     */
    int insert(TContraintsColor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_contraints_color
     *
     * @mbg.generated
     */
    int insertSelective(TContraintsColor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_contraints_color
     *
     * @mbg.generated
     */
    TContraintsColor selectByPrimaryKey(Integer fContraintsId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_contraints_color
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TContraintsColor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_contraints_color
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TContraintsColor record);
}