package com.learn.paik.dao;

import com.learn.entity.TCourseFlag;

public interface TCourseFlagMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_course_flag
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer fCourseFlagId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_course_flag
     *
     * @mbg.generated
     */
    int insert(TCourseFlag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_course_flag
     *
     * @mbg.generated
     */
    int insertSelective(TCourseFlag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_course_flag
     *
     * @mbg.generated
     */
    TCourseFlag selectByPrimaryKey(Integer fCourseFlagId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_course_flag
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TCourseFlag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_course_flag
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TCourseFlag record);
}