package com.learn.paik.dao;

import com.learn.entity.TCourseWhere;
import com.learn.entity.TCourseWhereKey;

public interface TCourseWhereMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_course_where
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(TCourseWhereKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_course_where
     *
     * @mbg.generated
     */
    int insert(TCourseWhere record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_course_where
     *
     * @mbg.generated
     */
    int insertSelective(TCourseWhere record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_course_where
     *
     * @mbg.generated
     */
    TCourseWhere selectByPrimaryKey(TCourseWhereKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_course_where
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TCourseWhere record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_course_where
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TCourseWhere record);
}