package com.learn.paik.dao;

import com.learn.entity.TempSchoolTimeTable;
import com.learn.entity.TempSchoolTimeTableKey;

public interface TempSchoolTimeTableMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table temp_school_time_table
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(TempSchoolTimeTableKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table temp_school_time_table
     *
     * @mbg.generated
     */
    int insert(TempSchoolTimeTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table temp_school_time_table
     *
     * @mbg.generated
     */
    int insertSelective(TempSchoolTimeTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table temp_school_time_table
     *
     * @mbg.generated
     */
    TempSchoolTimeTable selectByPrimaryKey(TempSchoolTimeTableKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table temp_school_time_table
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TempSchoolTimeTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table temp_school_time_table
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TempSchoolTimeTable record);
}