package com.learn.paik.dao;

import com.learn.entity.TGroupCourseNum;
import com.learn.entity.TGroupCourseNumKey;

public interface TGroupCourseNumMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_group_course_num
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(TGroupCourseNumKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_group_course_num
     *
     * @mbg.generated
     */
    int insert(TGroupCourseNum record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_group_course_num
     *
     * @mbg.generated
     */
    int insertSelective(TGroupCourseNum record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_group_course_num
     *
     * @mbg.generated
     */
    TGroupCourseNum selectByPrimaryKey(TGroupCourseNumKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_group_course_num
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TGroupCourseNum record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_group_course_num
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TGroupCourseNum record);
}