package com.learn.paik.dao;

import com.learn.entity.TTeacherCourseKey;

public interface TTeacherCourseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_teacher_course
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(TTeacherCourseKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_teacher_course
     *
     * @mbg.generated
     */
    int insert(TTeacherCourseKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_teacher_course
     *
     * @mbg.generated
     */
    int insertSelective(TTeacherCourseKey record);
}