package com.learn.paik.dao;

import com.learn.entity.TTemp;
import com.learn.entity.TTempKey;

public interface TTempMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_temp
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(TTempKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_temp
     *
     * @mbg.generated
     */
    int insert(TTemp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_temp
     *
     * @mbg.generated
     */
    int insertSelective(TTemp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_temp
     *
     * @mbg.generated
     */
    TTemp selectByPrimaryKey(TTempKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_temp
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TTemp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_temp
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TTemp record);
}