package com.learn.paik.dao;

import com.learn.entity.TWeek;

public interface TWeekMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_week
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer fWeekId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_week
     *
     * @mbg.generated
     */
    int insert(TWeek record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_week
     *
     * @mbg.generated
     */
    int insertSelective(TWeek record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_week
     *
     * @mbg.generated
     */
    TWeek selectByPrimaryKey(Integer fWeekId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_week
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TWeek record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_week
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TWeek record);
}